steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/vs-code-proj/my-ai-app-test/my-huggingface-web-app', '.']

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/vs-code-proj/my-ai-app-test/my-huggingface-web-app']

  # Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'my-huggingface-web-app',
      '--image', 'asia-south1-docker.pkg.dev/vs-code-proj/my-ai-app-test/my-huggingface-web-app',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--set-env-vars', 'HUGGING_FACE_API_KEY=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,DB_HOST=34.16.11.198,DB_USER=root,DB_PASSWORD=Sathi@1993,DB_NAME=demo-gen,BASIC_AUTH_USERNAME=admin,BASIC_AUTH_PASSWORD=admin'
    ]

logsBucket: 'cloubuild-logs'

images:
  - 'asia-south1-docker.pkg.dev/vs-code-proj/my-ai-app-test/my-huggingface-web-app' 
