steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/vs-code-proj/my-ai-app-test/my-huggingface-web-app', '.']

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/vs-code-proj/my-ai-app-test/my-huggingface-web-app']

  # Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy my-huggingface-web-app \
          --image asia-south1-docker.pkg.dev/vs-code-proj/my-ai-app-test/my-huggingface-web-app \
          --platform managed \
          --region asia-south1 \
          --allow-unauthenticated \
          --set-env-vars USERNAME=$$USERNAME,PASSWORD=$$PASSWORD,HUGGING_FACE_API_KEY=$$HUGGING_FACE_API_KEY
    secretEnv: ['USERNAME', 'PASSWORD', 'HUGGING_FACE_API_KEY']

availableSecrets:
  secretManager:
    - versionName: projects/vs-code-proj/secrets/USERNAME/versions/latest
      env: 'USERNAME'
    - versionName: projects/vs-code-proj/secrets/PASSWORD/versions/latest
      env: 'PASSWORD'
    - versionName: projects/vs-code-proj/secrets/HUGGING_FACE_API_KEY/versions/latest
      env: 'HUGGING_FACE_API_KEY'

logsBucket: 'cloubuild-logs'

images:
  - 'asia-south1-docker.pkg.dev/vs-code-proj/my-ai-app-test/my-huggingface-web-app'

serviceAccount: "ci-cd-service-account@${PROJECT_ID}.iam.gserviceaccount.com"
